using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace EDIConverterWeb.Data
{
    public class Item
    {
        public int Id { get; set; }
        public int Index { get; set; }
        public int QuantityOrdered { get; set; }//up to 15 digits
        public string UnitOfMeasure { get; set; }//for now it's a string cuz it's generated by the 850

        [Precision(18,2)]
        public decimal UnitPrice { get; set; }
        public string ItemNumber { get; set; }
        public int PurchaseOrderAcknowledgementId { get; set; }

        [JsonIgnore]
        public PurchaseOrderAcknowledgement PurchaseOrderAcknowledgement { get; set; }
    }
}
